image: gitlab.zengenti.com:4567/ops/zengenti-dind:latest

stages:
  - storybook-latest-build
  - latest-build
  - live-build

variables:
  DOCKER_DRIVER: overlay2
  STORYBOOK: ''
  APP_BUILDER_IMAGE: '$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME/app-builder'
  APP_IMAGE: '$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME/app'
  STORYBOOK_BUILDER_IMAGE: '$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME/storybook-builder'
  STORYBOOK_IMAGE: '$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME/storybook'
  MASTER_APP: '$CI_REGISTRY_IMAGE/master/app'

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab.zengenti.com:4567

build-latest-code:
  stage: latest-build
  except:
    - tags
    - ^release-.*$
  script:
    - docker pull $APP_BUILDER_IMAGE:latest || true
    - echo "{\"commitRef\":\"$CI_COMMIT_SHA\",\"pipelineIID\":\"$CI_PIPELINE_IID\",\"pipelineUrl\":\"$CI_PIPELINE_URL\",\"buildNo\":\"$CI_PIPELINE_ID\",\"branchName\":\"$CI_COMMIT_REF_NAME\",\"registryImage\":\"$CI_REGISTRY_IMAGE\"}" > version.json
    - docker build --force-rm --cache-from $APP_BUILDER_IMAGE:latest -t $APP_BUILDER_IMAGE:latest -f docker/nodebuilder.DockerFile .
    - docker push $APP_BUILDER_IMAGE:latest
    - docker pull $APP_IMAGE:latest || true
    - docker build --force-rm --cache-from $APP_IMAGE:latest -t $APP_IMAGE:latest --build-arg builder_image=$APP_BUILDER_IMAGE:latest -f docker/ci-build.DockerFile .
    - docker push $APP_IMAGE:latest
  environment:
    name: latest
    url: http://dev.preview.$CI_PROJECT_NAME.contensis.cloud

build-storybook:
  stage: storybook-latest-build
  except:
    - tags
    - ^release-.*$
  only:
    variables:
      - $STORYBOOK == 'true'
  script:
    - docker pull $STORYBOOK_BUILDER_IMAGE:latest || true
    - docker build --compress --force-rm --cache-from $STORYBOOK_BUILDER_IMAGE:latest -t $STORYBOOK_BUILDER_IMAGE:latest -f docker/storybook-builder.DockerFile .
    - docker push $STORYBOOK_BUILDER_IMAGE:latest
    - docker build --compress --force-rm -t $STORYBOOK_IMAGE:latest --build-arg builder_image=$STORYBOOK_BUILDER_IMAGE:latest -f  docker/storybook-http.DockerFile .
    - docker push $STORYBOOK_IMAGE:latest
  environment:
    name: storybook
    url: http://storybook.latest.$CI_PROJECT_NAME.contensis.cloud

build-live-code-for-production:
  stage: live-build
  only:
    - tags
    - ^release-.*$
    - $STORYBOOK == ''
  except:
    - branches
  script:
    - docker pull "$MASTER_APP:latest"
    - docker tag "$MASTER_APP:latest" "$MASTER_APP:release"
    - docker push "$MASTER_APP:release"
  environment:
    name: live
    url: http://preview.$CI_PROJECT_NAME.contensis.cloud
